apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: pony-pet
  namespace: mae
  labels:
    app.kubernetes.io/part-of: pony-pet
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: java
    apps.tanzu.vmware.com/workload-type: web
    workload-intent: code-analysis
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_sub_path
    value: config/mae/pony-pet
  source:
    git:
      url: ssh://git@github.com/Mpluya/config-pony-pet.git
      ref:
        branch: main

